[book]
authors = ["Nous Research"]
language = "en"
src = "src"
title = "Psyche"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["./theme/psyche.css"]
default-theme = "psyche-light"
preferred-dark-theme = "psyche-dark"

[output.linkcheck]
