[project]
name = "psyche-runtime"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
  "torch==2.9.1",
  "safetensors==0.7.0",
]

[build-system]
requires = ["uv_build<0.9"]
build-backend = "uv_build"
